WEDGE_LENGTH = 100;
WEDGE_WIDTH = 22.5;
WEDGE_COMMON_HEIGHT = 16;

WEDGE_SLOPE_END_HEIGHT_ADDITION = 4;

// TODO Grip on the slope side

hull() {
  cube([WEDGE_LENGTH, WEDGE_WIDTH, WEDGE_COMMON_HEIGHT]);
  translate([WEDGE_LENGTH, 0, WEDGE_COMMON_HEIGHT + WEDGE_SLOPE_END_HEIGHT_ADDITION]) {
    cube([0.00000000001, WEDGE_WIDTH, 0.00000000001]);
  }
}
